'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { gsap } from 'gsap';
import { ArrowUpRight, Cloud, CloudRain, Eye, Heart, LocateFixed, MapPin, Moon, Navigation, RefreshCw, Search, Settings2, Snowflake, Sun, Thermometer, Wind, X } from 'lucide-react';
import type { Place, Units, WeatherData } from '@/lib/weather';
import { condition, formatDay, formatTime, label, temp, wind } from '@/lib/weather';
import WeatherScene from '@/components/WeatherScene';
import WeatherMap from '@/components/WeatherMap';

type WindUnit='km/h'|'mph'|'m/s'; type Theme='auto'|'dark'|'light';
const defaultPlace:Place={name:'Karachi',country:'Pakistan',latitude:24.8607,longitude:67.0011};

export default function Home(){
 const [place,setPlace]=useState<Place>(defaultPlace),[data,setData]=useState<WeatherData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[suggestions,setSuggestions]=useState<Place[]>([]),[searchOpen,setSearchOpen]=useState(false),[selectedHour,setSelectedHour]=useState(0);
 const [unit,setUnit]=useState<Units>('C'),[windUnit,setWindUnit]=useState<WindUnit>('km/h'),[theme,setTheme]=useState<Theme>('auto'),[favorites,setFavorites]=useState<Place[]>([]),[settings,setSettings]=useState(false),[mapOpen,setMapOpen]=useState(false);
 const searchRef=useRef<HTMLInputElement>(null),mainRef=useRef<HTMLDivElement>(null);
 const load=useCallback(async(p:Place)=>{setLoading(true);setError('');try{const qs=new URLSearchParams({lat:String(p.latitude),lon:String(p.longitude),name:p.name,country:p.country});const r=await fetch(`/api/weather?${qs}`,{cache:'no-store'});if(!r.ok)throw new Error('Weather service unavailable');setData(await r.json() as WeatherData);setPlace(p);setSelectedHour(0);}catch(e){setError(e instanceof Error?e.message:'Unable to load weather.')}finally{setLoading(false);}},[]);
 useEffect(()=>{const saved=localStorage.getItem('atmos-favorites');if(saved)try{setFavorites(JSON.parse(saved) as Place[])}catch{} const prefs=localStorage.getItem('atmos-prefs');if(prefs)try{const p=JSON.parse(prefs) as {unit?:Units;windUnit?:WindUnit;theme?:Theme};if(p.unit)setUnit(p.unit);if(p.windUnit)setWindUnit(p.windUnit);if(p.theme)setTheme(p.theme)}catch{} const slug=location.pathname.match(/^\/weather\/(.+)$/)?.[1];if(slug){fetch(`/api/geocode?q=${encodeURIComponent(slug.replaceAll('-',' '))}`).then(r=>r.json()).then(j=>{const p=j.results?.[0] as Place|undefined;if(p)load(p);else load(defaultPlace)}).catch(()=>load(defaultPlace));}else load(defaultPlace);},[load]);
 useEffect(()=>{localStorage.setItem('atmos-favorites',JSON.stringify(favorites));},[favorites]);
 useEffect(()=>{localStorage.setItem('atmos-prefs',JSON.stringify({unit,windUnit,theme}));document.documentElement.dataset.theme=theme;},[unit,windUnit,theme]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape')setSearchOpen(false)};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{if(searchOpen)requestAnimationFrame(()=>searchRef.current?.focus())},[searchOpen]);
 useEffect(()=>{if(query.trim().length<2){setSuggestions([]);return}const id=setTimeout(()=>fetch(`/api/geocode?q=${encodeURIComponent(query)}`).then(r=>r.json()).then(j=>setSuggestions((j.results??[]) as Place[])).catch(()=>setSuggestions([])),250);return()=>clearTimeout(id)},[query]);
 useEffect(()=>{if(!mainRef.current||!data)return;gsap.fromTo(mainRef.current.querySelectorAll('[data-reveal]'),{opacity:0,y:22},{opacity:1,y:0,duration:.65,stagger:.045,ease:'power3.out'});},[data]);
 const selected=data?.hourly[selectedHour]??data?.hourly[0];
 const fav=favorites.some(f=>f.name===place.name&&Math.abs(f.latitude-place.latitude)<.01);
 const saveLocation=(p:Place)=>{setPlace(p);load(p);setSearchOpen(false);setQuery('');history.replaceState(null,'',`/weather/${encodeURIComponent(p.name.toLowerCase().replaceAll(' ','-'))}`)};
 const toggleFav=()=>setFavorites(fav?favorites.filter(f=>f.name!==place.name):[...favorites,place]);
 const locate=()=>navigator.geolocation?.getCurrentPosition(pos=>saveLocation({name:'Your location',country:'',latitude:pos.coords.latitude,longitude:pos.coords.longitude}),()=>setError('Location permission was denied.'));
 if(loading&&!data)return <div className="boot"><div className="boot-orbit"><span/></div><div className="boot-copy"><small>ATMOS / WEATHER INTELLIGENCE</small><strong>LOCATING ATMOSPHERE</strong><span>{place.name.toUpperCase()} · SYNCING LIVE DATA</span></div></div>;
 if(!data)return <div className="fatal"><h1>Atmosphere unavailable.</h1><p>{error}</p><button onClick={()=>load(place)}><RefreshCw size={16}/> Retry</button></div>;
 const c=data.current,day=data.daily[0],max=data.daily[0].high,min=data.daily[0].low;
 const visual=selected?condition(selected.weatherCode):condition(c.weatherCode);
 const title=`Weather in ${place.name} — Current Conditions & Forecast`;
 return <div ref={mainRef} className="app-shell" data-visual={visual} data-theme={theme}>
   <header className="topbar"><a className="brand" href="/"><span className="brand-mark">A</span><span>ATMOS</span></a><nav><a href="#forecast">Forecast</a><a href="#atmosphere">Atmosphere</a><a href="#solar">Solar</a><button onClick={()=>setMapOpen(true)}>Map</button></nav><div className="top-actions"><button className="location-pill" onClick={locate}><LocateFixed size={15}/>{place.name}</button><button className={`heart ${fav?'active':''}`} onClick={toggleFav} aria-label="Favorite location"><Heart size={17} fill={fav?'currentColor':'none'}/></button><button onClick={()=>setSettings(true)} aria-label="Settings"><Settings2 size={17}/></button></div></header>
   <main>
    <section className="hero" data-reveal><div className="hero-copy"><div className="eyebrow"><i/> LIVE ATMOSPHERE · {data.timezone}</div><h1>Weather,<br/><em>with depth.</em></h1><p>Read the atmosphere as a living system — temperature, light, wind and precipitation translated into a spatial instrument.</p><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={18}/><span>Search a city, region or country</span><kbd>⌘ K</kbd></button><div className="hero-meta"><span><MapPin size={14}/>{place.name}, {place.country}</span><span>Updated {formatTime(data.updatedAt,data.timezone)}</span></div></div><div className="hero-scene"><WeatherScene weather={data} visual={visual}/><div className="scene-label scene-label-a"><span>CONDITION</span><b>{label(selected?.weatherCode??c.weatherCode)}</b></div><div className="scene-label scene-label-b"><span>WIND</span><b>{wind(selected?.windSpeed??c.windSpeed,windUnit)} {windUnit}</b></div><div className="hero-temp"><strong>{temp(selected?.temperature??c.temperature,unit)}°</strong><span>{unit} · feels {temp(c.feelsLike,unit)}°</span></div></div></section>
    <section className="timeline" data-reveal><div className="timeline-head"><div><small>TIME SCRUB</small><b>{selected?formatTime(selected.time,data.timezone):'Now'}</b></div><div className="timeline-context"><span>{label(selected?.weatherCode??c.weatherCode)}</span><strong>{temp(selected?.temperature??c.temperature,unit)}°</strong></div></div><div className="scrubber"><div className="scrub-line"/><div className="hours">{data.hourly.slice(0,24).map((h,i)=><button key={h.time} className={i===selectedHour?'selected':''} onClick={()=>setSelectedHour(i)}><span>{i===0?'NOW':formatTime(h.time,data.timezone)}</span><i style={{height:`${Math.max(12,h.precipitationProbability)}%`}}/><b>{temp(h.temperature,unit)}°</b></button>)}</div></div></section>
    <section id="forecast" className="forecast-block" data-reveal><div className="section-title"><div><small>01 / THE RHYTHM</small><h2>Forecast in motion</h2></div><p>Drag through time to see the atmosphere change. The scene, readings and forecast stay synchronized.</p></div><div className="forecast-grid"><div className="temp-chart"><div className="chart-head"><span>Temperature</span><b>{temp(c.temperature,unit)}° now</b></div><TemperatureGraph points={data.hourly.slice(0,24).map(x=>x.temperature)} unit={unit}/><div className="chart-labels"><span>NOW</span><span>06H</span><span>12H</span><span>18H</span><span>24H</span></div></div><div className="days">{data.daily.slice(0,10).map((d,i)=><div className={i===0?'today':''} key={d.date}><span>{i===0?'Today':formatDay(d.date,data.timezone)}</span><b>{weatherGlyph(d.weatherCode)}</b><span>{temp(d.high,unit)}° / {temp(d.low,unit)}°</span><small>{d.precipitationProbability}% rain</small></div>)}</div></div></section>
    <section id="atmosphere" className="metrics" data-reveal><div className="section-title"><div><small>02 / ATMOSPHERIC FIELD</small><h2>What the air is doing</h2></div><p>Every signal is live, normalized and presented with an accessible text value.</p></div><div className="metric-grid"><Metric icon={<Droplet/>} label="Humidity" value={`${c.humidity}%`} detail="Relative moisture" visual={<div className="liquid"><i style={{height:`${c.humidity}%`}}/></div>}/><Metric icon={<Wind size={19}/>} label="Wind" value={`${wind(c.windSpeed,windUnit)} ${windUnit}`} detail={`${compass(c.windDirection)}° · ${windDirection(c.windDirection)}`} visual={<div className="compass"><Navigation size={26} style={{transform:`rotate(${c.windDirection}deg)`}}/></div>}/><Metric icon={<Eye size={19}/>} label="Visibility" value={`${(c.visibility/1000).toFixed(1)} km`} detail="Atmospheric clarity" visual={<div className="rings"><i/><i/><i/></div>}/><Metric icon={<Gauge/>} label="Pressure" value={`${Math.round(c.pressure)} hPa`} detail="Surface reference" visual={<div className="pressure"><i/><i/><i/></div>}/><Metric icon={<Sun size={19}/>} label="UV index" value={c.uv.toFixed(1)} detail="Current ultraviolet" visual={<div className="gauge"><i style={{transform:`rotate(${Math.min(1,c.uv/11)*240-120}deg)`}}/></div>}/><Metric icon={<Cloud size={19}/>} label="Cloud cover" value={`${c.clouds}%`} detail="Sky coverage" visual={<div className="cloud-meter"><i style={{width:`${c.clouds}%`}}/></div>}/><Metric icon={<Thermometer size={19}/>} label="Dew point" value={`${temp(c.dewPoint,unit)}°`} detail="Condensation threshold" visual={<div className="dew"><i/></div>}/><Metric icon={<CloudRain size={19}/>} label="Precipitation" value={`${c.precipitation.toFixed(1)} mm`} detail={`${selected?.precipitationProbability??0}% probability`} visual={<div className="rain-bars">{Array.from({length:8},(_,i)=><i key={i} style={{height:`${12+((selected?.precipitationProbability??0)*((i%3)+1))/3}%`}}/> )}</div>}/></div></section>
    <section id="solar" className="solar" data-reveal><div className="solar-copy"><small>03 / LIGHT & ENERGY</small><h2>Follow the sun.</h2><p>The solar arc is derived from the day’s sunrise and sunset. Its position gives a simple visual read of daylight progress.</p><div className="sun-stats"><div><span>Sunrise</span><b>{formatTime(day.sunrise,data.timezone)}</b></div><div><span>Sunset</span><b>{formatTime(day.sunset,data.timezone)}</b></div><div><span>Peak UV</span><b>{day.uv.toFixed(1)}</b></div></div></div><div className="solar-arc"><div className="arc-line"/><div className="sun-orb"><Sun size={22}/></div><span className="arc-start">SUNRISE</span><span className="arc-end">SUNSET</span><strong>{Math.round(daylightProgress(day.sunrise,day.sunset))}%</strong><small>daylight</small></div></section>
    <section className="astronomy" data-reveal><div><small>04 / NIGHT FIELD</small><h2>After the light.</h2><p>Moon phase and night context are kept deliberately quiet so the weather remains the primary instrument.</p></div><div className="moon"><div className="moon-disc"/><div><span>Moon phase</span><b>{moonPhase()}</b><small>Illumination estimated from current date</small></div></div></section>
    <section className="map-section" data-reveal><div><small>05 / WEATHER MAP</small><h2>Atmosphere, from above.</h2><p>Explore the selected location in context. Switch layers to temperature, precipitation, wind or cloud cover.</p></div><button onClick={()=>setMapOpen(true)}>Open interactive map <ArrowUpRight size={17}/></button></section>
   </main>
   <footer><span>ATMOS / WEATHER INTELLIGENCE</span><span>LIVE DATA · OPEN-METEO</span><span>REACT · THREE.JS · GSAP</span></footer>
   {searchOpen&&<div className="overlay" onMouseDown={()=>setSearchOpen(false)}><div className="search-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-search"><Search/><input ref={searchRef} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any city or country…"/><kbd>ESC</kbd></div><div className="search-results">{suggestions.map((s,i)=><button key={`${s.name}-${i}`} onClick={()=>saveLocation(s)}><MapPin size={17}/><span><b>{s.name}</b><small>{s.admin1?`${s.admin1}, `:''}{s.country}</small></span><ArrowUpRight size={15}/></button>)}{query.length>1&&!suggestions.length&&<p>No matching locations.</p>}{!query&&<div className="quick-search"><span>QUICK LOCATIONS</span>{favorites.map(f=><button key={f.name} onClick={()=>saveLocation(f)}><Heart size={14}/>{f.name}</button>)}<button onClick={locate}><LocateFixed size={14}/>Use my location</button></div>}</div></div></div>}
   {settings&&<div className="overlay" onMouseDown={()=>setSettings(false)}><div className="settings-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSettings(false)}><X/></button><small>PREFERENCES</small><h2>Shape your Atmos.</h2><Setting title="Temperature"><div className="segmented"><button className={unit==='C'?'on':''} onClick={()=>setUnit('C')}>°C</button><button className={unit==='F'?'on':''} onClick={()=>setUnit('F')}>°F</button></div></Setting><Setting title="Wind"><select value={windUnit} onChange={e=>setWindUnit(e.target.value as WindUnit)}><option>km/h</option><option>mph</option><option>m/s</option></select></Setting><Setting title="Theme"><div className="segmented"><button className={theme==='auto'?'on':''} onClick={()=>setTheme('auto')}>Auto</button><button className={theme==='dark'?'on':''} onClick={()=>setTheme('dark')}>Dark</button><button className={theme==='light'?'on':''} onClick={()=>setTheme('light')}>Light</button></div></Setting><Setting title="Saved locations"><div className="saved">{favorites.length?favorites.map(f=><button key={f.name} onClick={()=>saveLocation(f)}>{f.name}<X size={13} onClick={e=>{e.stopPropagation();setFavorites(favorites.filter(x=>x.name!==f.name))}}/></button>):<span>No favorites yet.</span>}</div></Setting></div></div>}
   {mapOpen&&<div className="overlay map-overlay" onMouseDown={()=>setMapOpen(false)}><div className="map-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setMapOpen(false)}><X/></button><div className="map-heading"><div><small>WEATHER MAP</small><h2>{place.name}</h2></div><span>Live location context</span></div><WeatherMap lat={place.latitude} lon={place.longitude}/></div></div>}
   {error&&<div className="toast"><span>{error}</span><button onClick={()=>setError('')}><X size={14}/></button></div>}
 </div>;
}

function Metric({icon,label,value,detail,visual}:{icon:React.ReactNode;label:string;value:string;detail:string;visual:React.ReactNode}){return <article className="metric"><div className="metric-head"><span>{icon}{label}</span><b>{value}</b></div><div className="metric-visual">{visual}</div><small>{detail}</small></article>}
function Setting({title,children}:{title:string;children:React.ReactNode}){return <div className="setting"><b>{title}</b>{children}</div>}
function TemperatureGraph({points,unit}:{points:number[];unit:Units}){const min=Math.min(...points),max=Math.max(...points),range=Math.max(1,max-min),path=points.map((p,i)=>`${i*(100/(points.length-1))},${90-((p-min)/range)*70}`).join(' ');return <svg className="temperature-graph" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Hourly temperature graph"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopOpacity=".22"/><stop offset="1" stopOpacity="0"/></linearGradient></defs><polyline points={`0,100 ${path} 100,100`} fill="url(#fill)" stroke="none"/><polyline points={path} fill="none" stroke="currentColor" strokeWidth="1.3" vectorEffect="non-scaling-stroke"/></svg>}
function weatherGlyph(code:number){if(code===0)return <Sun/>;if(code<=3)return <Cloud/>;if(code<=67)return <CloudRain/>;if(code<=77)return <Snowflake/>;return <CloudRain/>}
function Droplet(){return <span className="drop-icon">◒</span>} function Gauge(){return <span className="gauge-icon">◉</span>}
function compass(d:number){return Math.round(d)%360} function windDirection(d:number){return ['N','NE','E','SE','S','SW','W','NW'][Math.round(d/45)%8]}
function daylightProgress(a:string,b:string){const now=Date.now(),start=new Date(a).getTime(),end=new Date(b).getTime();return Math.max(0,Math.min(100,(now-start)/(end-start)*100))}
function moonPhase(){const known=new Date('2000-01-06T18:14:00Z').getTime(),days=(Date.now()-known)/86400000,cycle=29.530588853,age=((days%cycle)+cycle)%cycle;if(age<1.85)return'New moon';if(age<7.38)return'Waxing crescent';if(age<9.23)return'First quarter';if(age<14.77)return'Waxing gibbous';if(age<16.62)return'Full moon';if(age<22.15)return'Waning gibbous';if(age<23.99)return'Last quarter';return'Waning crescent';}
