import { z } from 'zod';

export type Place={name:string;country:string;admin1?:string;latitude:number;longitude:number};
export type Units='C'|'F';
export type WeatherData={location:Place;timezone:string;current:CurrentWeather;hourly:HourlyForecast[];daily:DailyForecast[];updatedAt:string};
export type CurrentWeather={time:string;temperature:number;feelsLike:number;humidity:number;windSpeed:number;windDirection:number;pressure:number;visibility:number;uv:number;clouds:number;precipitation:number;weatherCode:number;isDay:boolean;dewPoint:number};
export type HourlyForecast={time:string;temperature:number;precipitationProbability:number;precipitation:number;windSpeed:number;windDirection:number;weatherCode:number;humidity:number;uv:number};
export type DailyForecast={date:string;high:number;low:number;weatherCode:number;precipitationProbability:number;precipitation:number;windSpeed:number;sunrise:string;sunset:string;uv:number};

const currentSchema=z.object({time:z.string(),temperature_2m:z.number(),relative_humidity_2m:z.number(),apparent_temperature:z.number(),wind_speed_10m:z.number(),wind_direction_10m:z.number(),surface_pressure:z.number(),visibility:z.number(),uv_index:z.number().optional(),cloud_cover:z.number(),precipitation:z.number(),weather_code:z.number(),is_day:z.number(),dew_point_2m:z.number()});
const hourlySchema=z.object({time:z.array(z.string()),temperature_2m:z.array(z.number()),precipitation_probability:z.array(z.number()),precipitation:z.array(z.number()),wind_speed_10m:z.array(z.number()),wind_direction_10m:z.array(z.number()),weather_code:z.array(z.number()),relative_humidity_2m:z.array(z.number()),uv_index:z.array(z.number())});
const dailySchema=z.object({time:z.array(z.string()),weather_code:z.array(z.number()),temperature_2m_max:z.array(z.number()),temperature_2m_min:z.array(z.number()),sunrise:z.array(z.string()),sunset:z.array(z.string()),uv_index_max:z.array(z.number()),precipitation_sum:z.array(z.number()),precipitation_probability_max:z.array(z.number()),wind_speed_10m_max:z.array(z.number())});
export const apiSchema=z.object({timezone:z.string(),current:currentSchema,hourly:hourlySchema,daily:dailySchema});

export function transformWeather(place:Place, raw:unknown):WeatherData{const data=apiSchema.parse(raw);const h=data.hourly;const d=data.daily;return{location:place,timezone:data.timezone,updatedAt:data.current.time,current:{time:data.current.time,temperature:data.current.temperature_2m,feelsLike:data.current.apparent_temperature,humidity:data.current.relative_humidity_2m,windSpeed:data.current.wind_speed_10m,windDirection:data.current.wind_direction_10m,pressure:data.current.surface_pressure,visibility:data.current.visibility,uv:data.current.uv_index??h.uv_index[0]??0,clouds:data.current.cloud_cover,precipitation:data.current.precipitation,weatherCode:data.current.weather_code,isDay:data.current.is_day===1,dewPoint:data.current.dew_point_2m},hourly:h.time.slice(0,48).map((time,i)=>({time,temperature:h.temperature_2m[i],precipitationProbability:h.precipitation_probability[i],precipitation:h.precipitation[i],windSpeed:h.wind_speed_10m[i],windDirection:h.wind_direction_10m[i],weatherCode:h.weather_code[i],humidity:h.relative_humidity_2m[i],uv:h.uv_index[i]})),daily:d.time.map((date,i)=>({date,high:d.temperature_2m_max[i],low:d.temperature_2m_min[i],weatherCode:d.weather_code[i],precipitationProbability:d.precipitation_probability_max[i],precipitation:d.precipitation_sum[i],windSpeed:d.wind_speed_10m_max[i],sunrise:d.sunrise[i],sunset:d.sunset[i],uv:d.uv_index_max[i]}))};}
export function label(code:number){if(code===0)return'Clear sky';if(code<=3)return'Partly cloudy';if(code<=48)return'Fog';if(code<=67)return'Rain';if(code<=77)return'Snow';if(code<=82)return'Showers';return'Thunderstorm';}
export function condition(code:number):'clear'|'cloud'|'rain'|'snow'|'storm'|'fog'{if(code===0)return'clear';if(code<=3)return'cloud';if(code<=48)return'fog';if(code<=67)return'rain';if(code<=77)return'snow';if(code<=82)return'rain';return'storm';}
export function temp(v:number,u:Units){return Math.round(u==='C'?v:v*9/5+32);}
export function wind(v:number,u:'km/h'|'mph'|'m/s'){return u==='km/h'?Math.round(v):u==='mph'?Math.round(v*.621371):Number((v/3.6).toFixed(1));}
export function formatTime(iso:string,timeZone?:string){return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit',timeZone}).format(new Date(iso));}
export function formatDay(iso:string,timeZone?:string){return new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',timeZone}).format(new Date(iso));}
